http
{
	server
	{
		listen 127.0.0.1:8800;
		listen 8801;
		server_name localhost;
		client_body_size 100 000 000;
		index index.html;
		root docs/fusion_web/;
		location /
		{
			root /data/www;
		}
	}
}
