http
{
	server
	{
		listen 127.0.0.1:8080;
		listen 127.0.0.1:8081;
		listen 127.0.0.1:8082;
		listen 127.0.0.1:8083;
		server_name localhost;
		client_body_size 100 000 000;
		root /data/www;
		index index.html;
		location /images/download
		{
			root /data/download;
			method POST, DELETE;
			autoindex on;
		}
		location /images
		{
			root /data/images;
			method GET;
			autoindex on;
		}
		location /cgi-bin
		{
			root ./;
			method GET;
			autoindex on;
			CGI_PATH /usr/bin/python3 /bin/bash;
			CGI_EXT .py .sh;
		}
	}
	server
	{
		listen 0.0.0.0:8800;
		listen      0.0.0.0:8802	;
		server_name test_config      ;
		location /images
		{
			root /data/images/example;
			method GET;
			autoindex on;
		}
		location /images  /down     load
		{
			root /data/downloads/example;
			method POST,    DELETE;
			autoindex 	on     ;
		}
	}
	server
	{
		listen 0.0.0.0:8803;
		server_name test;
		location /download
		{
			root /data/www/test;
			method POST, PUT, DELETE;
			autoindex on;
		}
	}
}
